// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Data;

#nullable disable

namespace WeatherApp.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20230719204837_dataseedWeatherdata")]
    partial class dataseedWeatherdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherApp.Data.DtoDb.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cloud")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("WindDirection")
                        .HasColumnType("int");

                    b.Property<int>("WindSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cloud = 78,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2658),
                            Humidity = 31,
                            Temperature = 4,
                            WindDirection = 212,
                            WindSpeed = 385
                        },
                        new
                        {
                            Id = 2,
                            Cloud = 9,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2831),
                            Humidity = 62,
                            Temperature = 20,
                            WindDirection = 253,
                            WindSpeed = 376
                        },
                        new
                        {
                            Id = 3,
                            Cloud = 49,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2841),
                            Humidity = 1,
                            Temperature = 4,
                            WindDirection = 201,
                            WindSpeed = 297
                        },
                        new
                        {
                            Id = 4,
                            Cloud = 88,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2851),
                            Humidity = 87,
                            Temperature = 17,
                            WindDirection = 17,
                            WindSpeed = 59
                        },
                        new
                        {
                            Id = 5,
                            Cloud = 64,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2860),
                            Humidity = 23,
                            Temperature = 21,
                            WindDirection = 319,
                            WindSpeed = 317
                        },
                        new
                        {
                            Id = 6,
                            Cloud = 53,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2870),
                            Humidity = 87,
                            Temperature = 9,
                            WindDirection = 77,
                            WindSpeed = 257
                        },
                        new
                        {
                            Id = 7,
                            Cloud = 41,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2879),
                            Humidity = 17,
                            Temperature = 14,
                            WindDirection = 74,
                            WindSpeed = 495
                        },
                        new
                        {
                            Id = 8,
                            Cloud = 13,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2891),
                            Humidity = 28,
                            Temperature = 11,
                            WindDirection = 171,
                            WindSpeed = 180
                        },
                        new
                        {
                            Id = 9,
                            Cloud = 79,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2899),
                            Humidity = 1,
                            Temperature = 24,
                            WindDirection = 292,
                            WindSpeed = 358
                        },
                        new
                        {
                            Id = 10,
                            Cloud = 50,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2910),
                            Humidity = 57,
                            Temperature = 34,
                            WindDirection = 277,
                            WindSpeed = 447
                        },
                        new
                        {
                            Id = 11,
                            Cloud = 85,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2919),
                            Humidity = 97,
                            Temperature = 28,
                            WindDirection = 45,
                            WindSpeed = 498
                        },
                        new
                        {
                            Id = 12,
                            Cloud = 0,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2928),
                            Humidity = 79,
                            Temperature = 11,
                            WindDirection = 148,
                            WindSpeed = 374
                        },
                        new
                        {
                            Id = 13,
                            Cloud = 27,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2937),
                            Humidity = 18,
                            Temperature = 0,
                            WindDirection = 175,
                            WindSpeed = 15
                        },
                        new
                        {
                            Id = 14,
                            Cloud = 18,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2946),
                            Humidity = 82,
                            Temperature = 1,
                            WindDirection = 111,
                            WindSpeed = 366
                        },
                        new
                        {
                            Id = 15,
                            Cloud = 31,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2956),
                            Humidity = 8,
                            Temperature = 9,
                            WindDirection = 284,
                            WindSpeed = 489
                        },
                        new
                        {
                            Id = 16,
                            Cloud = 84,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2964),
                            Humidity = 20,
                            Temperature = 15,
                            WindDirection = 24,
                            WindSpeed = 499
                        },
                        new
                        {
                            Id = 17,
                            Cloud = 57,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2972),
                            Humidity = 87,
                            Temperature = 4,
                            WindDirection = 347,
                            WindSpeed = 435
                        },
                        new
                        {
                            Id = 18,
                            Cloud = 9,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(2983),
                            Humidity = 21,
                            Temperature = 34,
                            WindDirection = 102,
                            WindSpeed = 486
                        },
                        new
                        {
                            Id = 19,
                            Cloud = 64,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3049),
                            Humidity = 41,
                            Temperature = 20,
                            WindDirection = 6,
                            WindSpeed = 321
                        },
                        new
                        {
                            Id = 20,
                            Cloud = 4,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3059),
                            Humidity = 23,
                            Temperature = 33,
                            WindDirection = 131,
                            WindSpeed = 15
                        },
                        new
                        {
                            Id = 21,
                            Cloud = 65,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3071),
                            Humidity = 47,
                            Temperature = 29,
                            WindDirection = 221,
                            WindSpeed = 178
                        },
                        new
                        {
                            Id = 22,
                            Cloud = 92,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3080),
                            Humidity = 20,
                            Temperature = 5,
                            WindDirection = 281,
                            WindSpeed = 408
                        },
                        new
                        {
                            Id = 23,
                            Cloud = 60,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3092),
                            Humidity = 98,
                            Temperature = 23,
                            WindDirection = 263,
                            WindSpeed = 213
                        },
                        new
                        {
                            Id = 24,
                            Cloud = 55,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3101),
                            Humidity = 82,
                            Temperature = 26,
                            WindDirection = 11,
                            WindSpeed = 494
                        },
                        new
                        {
                            Id = 25,
                            Cloud = 88,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3110),
                            Humidity = 13,
                            Temperature = 6,
                            WindDirection = 192,
                            WindSpeed = 399
                        },
                        new
                        {
                            Id = 26,
                            Cloud = 2,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3120),
                            Humidity = 12,
                            Temperature = 3,
                            WindDirection = 170,
                            WindSpeed = 268
                        },
                        new
                        {
                            Id = 27,
                            Cloud = 72,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3131),
                            Humidity = 82,
                            Temperature = 26,
                            WindDirection = 214,
                            WindSpeed = 483
                        },
                        new
                        {
                            Id = 28,
                            Cloud = 13,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3141),
                            Humidity = 47,
                            Temperature = 35,
                            WindDirection = 249,
                            WindSpeed = 167
                        },
                        new
                        {
                            Id = 29,
                            Cloud = 19,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3150),
                            Humidity = 1,
                            Temperature = 17,
                            WindDirection = 216,
                            WindSpeed = 339
                        },
                        new
                        {
                            Id = 30,
                            Cloud = 77,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3162),
                            Humidity = 43,
                            Temperature = 9,
                            WindDirection = 21,
                            WindSpeed = 371
                        },
                        new
                        {
                            Id = 31,
                            Cloud = 43,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3171),
                            Humidity = 66,
                            Temperature = 0,
                            WindDirection = 91,
                            WindSpeed = 128
                        },
                        new
                        {
                            Id = 32,
                            Cloud = 52,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3181),
                            Humidity = 76,
                            Temperature = 27,
                            WindDirection = 134,
                            WindSpeed = 425
                        },
                        new
                        {
                            Id = 33,
                            Cloud = 68,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3192),
                            Humidity = 16,
                            Temperature = 9,
                            WindDirection = 247,
                            WindSpeed = 498
                        },
                        new
                        {
                            Id = 34,
                            Cloud = 65,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3204),
                            Humidity = 92,
                            Temperature = 33,
                            WindDirection = 23,
                            WindSpeed = 335
                        },
                        new
                        {
                            Id = 35,
                            Cloud = 66,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3214),
                            Humidity = 2,
                            Temperature = 28,
                            WindDirection = 172,
                            WindSpeed = 116
                        },
                        new
                        {
                            Id = 36,
                            Cloud = 20,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3223),
                            Humidity = 41,
                            Temperature = 7,
                            WindDirection = 242,
                            WindSpeed = 371
                        },
                        new
                        {
                            Id = 37,
                            Cloud = 15,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3232),
                            Humidity = 62,
                            Temperature = 7,
                            WindDirection = 54,
                            WindSpeed = 128
                        },
                        new
                        {
                            Id = 38,
                            Cloud = 23,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3243),
                            Humidity = 74,
                            Temperature = 14,
                            WindDirection = 3,
                            WindSpeed = 173
                        },
                        new
                        {
                            Id = 39,
                            Cloud = 97,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3252),
                            Humidity = 68,
                            Temperature = 2,
                            WindDirection = 146,
                            WindSpeed = 190
                        },
                        new
                        {
                            Id = 40,
                            Cloud = 98,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3262),
                            Humidity = 19,
                            Temperature = 29,
                            WindDirection = 171,
                            WindSpeed = 246
                        },
                        new
                        {
                            Id = 41,
                            Cloud = 31,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3273),
                            Humidity = 68,
                            Temperature = 31,
                            WindDirection = 147,
                            WindSpeed = 141
                        },
                        new
                        {
                            Id = 42,
                            Cloud = 73,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3283),
                            Humidity = 6,
                            Temperature = 19,
                            WindDirection = 265,
                            WindSpeed = 315
                        },
                        new
                        {
                            Id = 43,
                            Cloud = 32,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3293),
                            Humidity = 62,
                            Temperature = 24,
                            WindDirection = 60,
                            WindSpeed = 161
                        },
                        new
                        {
                            Id = 44,
                            Cloud = 64,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3302),
                            Humidity = 50,
                            Temperature = 28,
                            WindDirection = 214,
                            WindSpeed = 199
                        },
                        new
                        {
                            Id = 45,
                            Cloud = 24,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3313),
                            Humidity = 51,
                            Temperature = 16,
                            WindDirection = 225,
                            WindSpeed = 455
                        },
                        new
                        {
                            Id = 46,
                            Cloud = 65,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3321),
                            Humidity = 57,
                            Temperature = 8,
                            WindDirection = 38,
                            WindSpeed = 450
                        },
                        new
                        {
                            Id = 47,
                            Cloud = 48,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3351),
                            Humidity = 97,
                            Temperature = 0,
                            WindDirection = 133,
                            WindSpeed = 66
                        },
                        new
                        {
                            Id = 48,
                            Cloud = 44,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3361),
                            Humidity = 73,
                            Temperature = 28,
                            WindDirection = 224,
                            WindSpeed = 453
                        },
                        new
                        {
                            Id = 49,
                            Cloud = 9,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3370),
                            Humidity = 18,
                            Temperature = 25,
                            WindDirection = 138,
                            WindSpeed = 279
                        },
                        new
                        {
                            Id = 50,
                            Cloud = 7,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3379),
                            Humidity = 60,
                            Temperature = 31,
                            WindDirection = 118,
                            WindSpeed = 361
                        },
                        new
                        {
                            Id = 51,
                            Cloud = 62,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3387),
                            Humidity = 15,
                            Temperature = 12,
                            WindDirection = 286,
                            WindSpeed = 302
                        },
                        new
                        {
                            Id = 52,
                            Cloud = 88,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3397),
                            Humidity = 14,
                            Temperature = 24,
                            WindDirection = 277,
                            WindSpeed = 279
                        },
                        new
                        {
                            Id = 53,
                            Cloud = 46,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3407),
                            Humidity = 1,
                            Temperature = 35,
                            WindDirection = 6,
                            WindSpeed = 476
                        },
                        new
                        {
                            Id = 54,
                            Cloud = 77,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3417),
                            Humidity = 88,
                            Temperature = 21,
                            WindDirection = 9,
                            WindSpeed = 451
                        },
                        new
                        {
                            Id = 55,
                            Cloud = 61,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3425),
                            Humidity = 71,
                            Temperature = 36,
                            WindDirection = 109,
                            WindSpeed = 176
                        },
                        new
                        {
                            Id = 56,
                            Cloud = 51,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3434),
                            Humidity = 23,
                            Temperature = 29,
                            WindDirection = 179,
                            WindSpeed = 132
                        },
                        new
                        {
                            Id = 57,
                            Cloud = 1,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3444),
                            Humidity = 34,
                            Temperature = 30,
                            WindDirection = 317,
                            WindSpeed = 242
                        },
                        new
                        {
                            Id = 58,
                            Cloud = 21,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3452),
                            Humidity = 29,
                            Temperature = 33,
                            WindDirection = 352,
                            WindSpeed = 163
                        },
                        new
                        {
                            Id = 59,
                            Cloud = 72,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3463),
                            Humidity = 12,
                            Temperature = 6,
                            WindDirection = 153,
                            WindSpeed = 309
                        },
                        new
                        {
                            Id = 60,
                            Cloud = 82,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3472),
                            Humidity = 51,
                            Temperature = 19,
                            WindDirection = 316,
                            WindSpeed = 77
                        },
                        new
                        {
                            Id = 61,
                            Cloud = 27,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3481),
                            Humidity = 26,
                            Temperature = 24,
                            WindDirection = 338,
                            WindSpeed = 446
                        },
                        new
                        {
                            Id = 62,
                            Cloud = 5,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3490),
                            Humidity = 74,
                            Temperature = 22,
                            WindDirection = 33,
                            WindSpeed = 11
                        },
                        new
                        {
                            Id = 63,
                            Cloud = 74,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3499),
                            Humidity = 97,
                            Temperature = 32,
                            WindDirection = 300,
                            WindSpeed = 18
                        },
                        new
                        {
                            Id = 64,
                            Cloud = 54,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3508),
                            Humidity = 74,
                            Temperature = 9,
                            WindDirection = 79,
                            WindSpeed = 2
                        },
                        new
                        {
                            Id = 65,
                            Cloud = 81,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3519),
                            Humidity = 95,
                            Temperature = 11,
                            WindDirection = 84,
                            WindSpeed = 426
                        },
                        new
                        {
                            Id = 66,
                            Cloud = 54,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3534),
                            Humidity = 13,
                            Temperature = 30,
                            WindDirection = 121,
                            WindSpeed = 371
                        },
                        new
                        {
                            Id = 67,
                            Cloud = 4,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3542),
                            Humidity = 75,
                            Temperature = 37,
                            WindDirection = 284,
                            WindSpeed = 202
                        },
                        new
                        {
                            Id = 68,
                            Cloud = 38,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3551),
                            Humidity = 35,
                            Temperature = 11,
                            WindDirection = 149,
                            WindSpeed = 183
                        },
                        new
                        {
                            Id = 69,
                            Cloud = 15,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3562),
                            Humidity = 95,
                            Temperature = 37,
                            WindDirection = 148,
                            WindSpeed = 411
                        },
                        new
                        {
                            Id = 70,
                            Cloud = 8,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3573),
                            Humidity = 42,
                            Temperature = 13,
                            WindDirection = 189,
                            WindSpeed = 172
                        },
                        new
                        {
                            Id = 71,
                            Cloud = 11,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3582),
                            Humidity = 41,
                            Temperature = 26,
                            WindDirection = 138,
                            WindSpeed = 473
                        },
                        new
                        {
                            Id = 72,
                            Cloud = 29,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3591),
                            Humidity = 17,
                            Temperature = 7,
                            WindDirection = 109,
                            WindSpeed = 78
                        },
                        new
                        {
                            Id = 73,
                            Cloud = 4,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3628),
                            Humidity = 13,
                            Temperature = 30,
                            WindDirection = 334,
                            WindSpeed = 216
                        },
                        new
                        {
                            Id = 74,
                            Cloud = 88,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3639),
                            Humidity = 0,
                            Temperature = 18,
                            WindDirection = 106,
                            WindSpeed = 244
                        },
                        new
                        {
                            Id = 75,
                            Cloud = 37,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3650),
                            Humidity = 28,
                            Temperature = 15,
                            WindDirection = 7,
                            WindSpeed = 163
                        },
                        new
                        {
                            Id = 76,
                            Cloud = 16,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3661),
                            Humidity = 2,
                            Temperature = 22,
                            WindDirection = 78,
                            WindSpeed = 37
                        },
                        new
                        {
                            Id = 77,
                            Cloud = 16,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3672),
                            Humidity = 2,
                            Temperature = 27,
                            WindDirection = 158,
                            WindSpeed = 271
                        },
                        new
                        {
                            Id = 78,
                            Cloud = 4,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3682),
                            Humidity = 68,
                            Temperature = 26,
                            WindDirection = 244,
                            WindSpeed = 383
                        },
                        new
                        {
                            Id = 79,
                            Cloud = 95,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3691),
                            Humidity = 56,
                            Temperature = 14,
                            WindDirection = 2,
                            WindSpeed = 484
                        },
                        new
                        {
                            Id = 80,
                            Cloud = 60,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3701),
                            Humidity = 16,
                            Temperature = 20,
                            WindDirection = 312,
                            WindSpeed = 453
                        },
                        new
                        {
                            Id = 81,
                            Cloud = 47,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3711),
                            Humidity = 76,
                            Temperature = 31,
                            WindDirection = 86,
                            WindSpeed = 459
                        },
                        new
                        {
                            Id = 82,
                            Cloud = 14,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3722),
                            Humidity = 50,
                            Temperature = 16,
                            WindDirection = 151,
                            WindSpeed = 496
                        },
                        new
                        {
                            Id = 83,
                            Cloud = 73,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3732),
                            Humidity = 61,
                            Temperature = 11,
                            WindDirection = 251,
                            WindSpeed = 114
                        },
                        new
                        {
                            Id = 84,
                            Cloud = 9,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3741),
                            Humidity = 16,
                            Temperature = 26,
                            WindDirection = 241,
                            WindSpeed = 147
                        },
                        new
                        {
                            Id = 85,
                            Cloud = 18,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3751),
                            Humidity = 29,
                            Temperature = 35,
                            WindDirection = 113,
                            WindSpeed = 288
                        },
                        new
                        {
                            Id = 86,
                            Cloud = 45,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3760),
                            Humidity = 59,
                            Temperature = 9,
                            WindDirection = 350,
                            WindSpeed = 482
                        },
                        new
                        {
                            Id = 87,
                            Cloud = 38,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3770),
                            Humidity = 23,
                            Temperature = 35,
                            WindDirection = 349,
                            WindSpeed = 11
                        },
                        new
                        {
                            Id = 88,
                            Cloud = 99,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3779),
                            Humidity = 36,
                            Temperature = 17,
                            WindDirection = 259,
                            WindSpeed = 0
                        },
                        new
                        {
                            Id = 89,
                            Cloud = 45,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3788),
                            Humidity = 64,
                            Temperature = 21,
                            WindDirection = 239,
                            WindSpeed = 175
                        },
                        new
                        {
                            Id = 90,
                            Cloud = 50,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3797),
                            Humidity = 37,
                            Temperature = 19,
                            WindDirection = 55,
                            WindSpeed = 364
                        },
                        new
                        {
                            Id = 91,
                            Cloud = 31,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3807),
                            Humidity = 91,
                            Temperature = 23,
                            WindDirection = 133,
                            WindSpeed = 69
                        },
                        new
                        {
                            Id = 92,
                            Cloud = 54,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3816),
                            Humidity = 64,
                            Temperature = 35,
                            WindDirection = 65,
                            WindSpeed = 481
                        },
                        new
                        {
                            Id = 93,
                            Cloud = 0,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3829),
                            Humidity = 30,
                            Temperature = 5,
                            WindDirection = 303,
                            WindSpeed = 440
                        },
                        new
                        {
                            Id = 94,
                            Cloud = 38,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3839),
                            Humidity = 93,
                            Temperature = 34,
                            WindDirection = 98,
                            WindSpeed = 455
                        },
                        new
                        {
                            Id = 95,
                            Cloud = 58,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3849),
                            Humidity = 35,
                            Temperature = 8,
                            WindDirection = 19,
                            WindSpeed = 89
                        },
                        new
                        {
                            Id = 96,
                            Cloud = 78,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3859),
                            Humidity = 18,
                            Temperature = 38,
                            WindDirection = 197,
                            WindSpeed = 68
                        },
                        new
                        {
                            Id = 97,
                            Cloud = 62,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3868),
                            Humidity = 32,
                            Temperature = 33,
                            WindDirection = 72,
                            WindSpeed = 71
                        },
                        new
                        {
                            Id = 98,
                            Cloud = 64,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3878),
                            Humidity = 25,
                            Temperature = 6,
                            WindDirection = 19,
                            WindSpeed = 125
                        },
                        new
                        {
                            Id = 99,
                            Cloud = 61,
                            DateTime = new DateTime(2023, 7, 19, 22, 48, 37, 16, DateTimeKind.Local).AddTicks(3888),
                            Humidity = 74,
                            Temperature = 11,
                            WindDirection = 356,
                            WindSpeed = 305
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
